### ISSUE TITLE
Datepicker: Keyboard navigation

### ISSUE THREAD

**Issue by JohanObrink** [sebgroup/green#483]
**Choose date button**

- [x] `Space, Enter`: Opens the date picker dialog and moves focus to the first select menu in the dialog.

**Date picker dialog**

- [x] `Esc`: Closes the date picker dialog and moves focus back to the “choose date” button.
- [ ] `Tab`: Moves focus to the next element in the dialog. Please note since the calendar uses role="grid", only one button in the calendar grid is in the tab sequence. Additionally, if focus is on the last focusable element, focus is next moved back to the first focusable element inside the date picker dialog.
- [ ] `Shift + Tab`: Same as above, but in reverse order.

**Date picker dialog: Month/year buttons**

- [ ] `Space, Enter`: Changes the month and/or year displayed.

**Date picker dialog: Date grid**

- [x] `Space, Enter`: Selects a date, closes the dialog, and moves focus back to the “Choose Date” button. Additionally updates the value of the Duet Date Picker input with the selected date, and adds selected date to “Choose Date” button label.
- [x] `Arrow up`: Moves focus to the same day of the previous week.
- [x] `Arrow down`: Moves focus to the same day of the next week.
- [x] `Arrow right`: Moves focus to the next day.
- [x] `Arrow left`: Moves focus to the previous day.
- [ ] `Home`: Moves focus to the first day (e.g Monday) of the current week.
- [ ] `End`: Moves focus to the last day (e.g. Sunday) of the current week.
- [x] `Page Up`: Changes the grid of dates to the previous month and sets focus on the same day of the same week.
- [ ] `Shift + Page Up`: Changes the grid of dates to the previous year and sets focus on the same day of the same week.
- [x] `Page Down`: Changes the grid of dates to the next month and sets focus on the same day of the same week.
- [ ] `Shift + Page Down`: Changes the grid of dates to the next year and sets focus on the same day of the same week.

**Date picker dialog: Close button**

- [x] `Space, Enter`: Closes the dialog, moves focus to “choose date” button, but does not update the date in input.
